---
title: "R Notebook"
output: html_notebook
---


```{r}

library(reticulate)

virtualenv_remove("rgee")

virtualenv_create("rgee", python = "/Users/julianflowers/Library/r-miniconda-arm64/bin/python3.10")

use_python("/Users/julianflowers/Library/r-miniconda-arm64/bin/python3.10")

use_virtualenv("rgee")



library(rgee)
library(rgeedim)
#library(rgeeExtra)
py_install(packages = 'earthengine-api', envname = '~/.virtualenvs/rgee')
Sys.setenv(EARTHENGINE_PYTHON="/Users/julianflowers/.virtualenvs/rgee/bin/python")



rgee::ee_Initialize(drive = TRUE, user = "julian.flowers12@gmail.com")
```

```{r}
rgee::ee$Image$Da
img <- rgee::ee$Image$Dataset$CGIAR_SRTM90_V4
Map$addLayer(log1p(img), list(min = 0, max = 7))
```


```{python}
import ee
ee.Authenticate(auth_mode="gcloud")
ee.Initialize()
```

```{python}
lst = ee.ImageCollection('MODIS/006/MOD11A1')
elv = ee.Image('USGS/SRTMGL1_003')


# Initial date of interest (inclusive).
i_date = '2017-01-01'

# Final date of interest (exclusive).
f_date = '2020-01-01'

# Selection of appropriate bands and dates for LST.
lst = lst.select('LST_Day_1km', 'QC_Day').filterDate(i_date, f_date)

# Define the urban location of interest as a point near Lyon, France.
u_lon = 4.8148
u_lat = 45.7758
u_poi = ee.Geometry.Point(u_lon, u_lat)

# Define the rural location of interest as a point away from the city.
r_lon = 5.175964
r_lat = 45.574064
r_poi = ee.Geometry.Point(r_lon, r_lat)
```


```{python}
scale = 1000  # scale in meters

# Print the elevation near Lyon, France.
elv_urban_point = elv.sample(u_poi, scale).first().get('elevation').getInfo()
print('Ground elevation at urban point:', elv_urban_point, 'm')

# Get the data for the pixel intersecting the point in urban area.
lst_u_poi = lst.getRegion(u_poi, scale).getInfo()

# Get the data for the pixel intersecting the point in rural area.
lst_r_poi = lst.getRegion(r_poi, scale).getInfo()

# Preview the result.
prev = lst_u_poi[:5]
```

```{r}

df <- reticulate::py$prev
df |>
  tibble::enframe() |>
  dplyr::slice(-1) |>
  tidyr::unnest("value") 

```




```{pytohn}
import pandas as pd

def ee_array_to_df(arr, list_of_bands):
    """Transforms client-side ee.Image.getRegion array to pandas.DataFrame."""
    df = pd.DataFrame(arr)

    # Rearrange the header.
    headers = df.iloc[0]
    df = pd.DataFrame(df.values[1:], columns=headers)

    # Remove rows without data inside.
    df = df[['longitude', 'latitude', 'time', *list_of_bands]].dropna()

    # Convert the data to numeric values.
    for band in list_of_bands:
        df[band] = pd.to_numeric(df[band], errors='coerce')

    # Convert the time field into a datetime.
    df['datetime'] = pd.to_datetime(df['time'], unit='ms')

    # Keep the columns of interest.
    df = df[['time','datetime',  *list_of_bands]]

    return df
  
  
  lst_df_urban = ee_array_to_df(lst_u_poi,['LST_Day_1km'])

def t_modis_to_celsius(t_modis):
    """Converts MODIS LST units to degrees Celsius."""
    t_celsius =  0.02*t_modis - 273.15
    return t_celsius
```


```{python}
# Apply the function to get temperature in celsius.
lst_df_urban['LST_Day_1km'] = lst_df_urban['LST_Day_1km'].apply(t_modis_to_celsius)

## Do the same for the rural point.
lst_df_rural = ee_array_to_df(lst_r_poi,['LST_Day_1km'])
lst_df_rural['LST_Day_1km'] = lst_df_rural['LST_Day_1km'].apply(t_modis_to_celsius)

lst_df_urban.head()

lst_img = lst.mean()

# Adjust for scale factor.
lst_img = lst_img.select('LST_Day_1km').multiply(0.02)

# Convert Kelvin to Celsius.
lst_img = lst_img.select('LST_Day_1km').add(-273.15)

roi = u_poi.buffer(1e6)
```


```{python}
import IPython
from IPython.display import Image

# Create a URL to the styled image for a region around France.
url = lst_img.getThumbUrl({
    'min': 10, 'max': 30, 'dimensions': 512, 'region': roi,
    'palette': ['blue', 'yellow', 'orange', 'red']})
print(url)

# Display the thumbnail land surface temperature in France.
print('\nPlease wait while the thumbnail loads, it may take a moment...')
i = Image(url=url)
i
```

```{r}
im <- reticulate::py$i

im

```

